### ISSUE TITLE
Is it possible to use the extension in a new tab?

### ISSUE THREAD

**Issue by linuxiaobai** [wangfenjin/Simple-WebSocket-Client#2]
In current version (0.1.4), there is no way to use in a new tab. I remember in a old version, it can be. Could you please help?

**Comment by wangfenjin** [comment]
Actually the initial version is a popup, then it breaks and show as a new tab, which fixed by https://github.com/wangfenjin/Simple-WebSocket-Client/pull/1

so ...

**Comment by linuxiaobai** [comment]
> Actually the initial version is a popup, then it breaks and show as a new tab, which fixed by #1
> 
> so ...

ok, thank you. If I need copy the code from the editor, then I need switch window. After switching back to firefox, the pop up dispeared with all content lost. Could you please add a option to allow user use a tab?

**Comment by wangfenjin** [comment]
I have submit version 0.1.15 for review, you can use the options page after it's approved

**Comment by linuxiaobai** [comment]
Great! I will take a try later. Many thanks:)

**Comment by wangfenjin** [comment]
<img width="996" alt="Screenshot 2022-10-09 at 10 48 05" src="https://user-images.githubusercontent.com/4160646/194735321-acaf971a-9c0a-46d1-bfe8-53fb14f55da6.png">

It should work now
