### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by fovea1959** [wangfenjin/Simple-WebSocket-Client#4]
no documentation on how to use this?

**Comment by wangfenjin** [comment]
Install the extension from Firefox marketplace, it’s easy to use

**Comment by fovea1959** [comment]
I have installed it. How do I access it?
 
 
  On Mon, Apr 17, 2023 at 9:47 PM, Wang ***@***.***> wrote:   


Install the extension from Firefox marketplace, it’s easy to use

**Comment by wangfenjin** [comment]
<img width="996" alt="Screenshot 2022-10-09 at 10 48 05" src="https://user-images.githubusercontent.com/4160646/194735321-acaf971a-9c0a-46d1-bfe8-53fb14f55da6.png">

There should be a button you can click, if not you can click the preference

**Comment by wangfenjin** [comment]
Sorry seems the preferences was deleted by new firefox version, but you can always click the button

<img width="278" alt="Screenshot 2023-04-18 at 11 14 50 AM" src="https://user-images.githubusercontent.com/4160646/232661996-5b9b417b-cbe0-4d87-94a8-2552690d44f3.png">

**Comment by fovea1959** [comment]
no button.



    On Monday, April 17, 2023 at 11:17:37 PM EDT, Wang Fenjin ***@***.***> wrote:  
 
 


Sorry seems the preferences was deleted by new firefox version, but you can always click the button
